# Base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy root workspace files for installing dependencies
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Copy server package.json separately (for pnpm workspace)
COPY apps/server/package.json ./apps/server/package.json

# Install dependencies including devDependencies
RUN pnpm install

# Copy server source code
COPY apps/server ./apps/server

# Set working dir to server
WORKDIR /app/apps/server

# Dev command
CMD ["pnpm", "dev"]
